import { useState } from 'react';
import clsx from 'clsx';
import {
  AlertCircle,
  ChevronDown,
  ChevronUp,
  ExternalLink,
} from 'lucide-react';

import { MarkdownRenderer } from './MarkdownRenderer';
import { TypingIndicator } from './TypingIndicator';
import { MessageActions } from './MessageActions';

import { formatTime } from '@/utils/formatDate';
import type { Message } from '@/types';

interface MessageBubbleProps {
  message: Message;
  isStreamingPlaceholder: boolean;
  showRegenerate: boolean;
  onRegenerate: () => void;
  isStreaming: boolean;
}

export function MessageBubble({
  message,
  isStreamingPlaceholder,
  showRegenerate,
  onRegenerate,
  isStreaming,
}: MessageBubbleProps) {
  const isUser = message.role === 'user';
  const [sourcesOpen, setSourcesOpen] = useState(false);

  const isEmpty =
    isStreamingPlaceholder &&
    message.content.length === 0 &&
    !message.error;

  return (
    <div
      className={clsx(
        'group flex w-full gap-3 px-1',
        isUser ? 'justify-end' : 'justify-start'
      )}
    >
      <div
        className={clsx(
          'flex flex-col max-w-[min(680px,88%)]',
          isUser && 'items-end'
        )}
      >
        <div
          className={clsx(
            'rounded-2xl px-4 py-2.5 text-[0.95rem]',
            isUser
              ? 'bg-accent-500 text-white dark:bg-accent-600 dark:text-white rounded-br-md'
              : 'bg-paper-alt dark:bg-ink-raised text-ink dark:text-paper rounded-bl-md'
          )}
        >
          {isEmpty ? (
            <TypingIndicator />
          ) : message.error ? (
            <div className="flex items-start gap-2 text-danger-light dark:text-danger-dark">
              <AlertCircle
                size={16}
                className="mt-0.5 shrink-0"
              />

              <span className="text-sm">
                {message.error}
              </span>
            </div>
          ) : isUser ? (
            <p className="whitespace-pre-wrap break-words">
              {message.content}
            </p>
          ) : message.image ? (
            <img
              src={`data:${message.image.mimeType};base64,${message.image.data}`}
              alt={
                message.image.alt ??
                'Generated by Atlas AI'
              }
              className="max-w-full rounded-xl object-contain"
            />
          ) : (
            <MarkdownRenderer
              content={message.content}
            />
          )}

          {message.stopped && (
            <p className="mt-1.5 text-xs italic opacity-70">
              Generation stopped.
            </p>
          )}
        </div>

        {message.research &&
          message.research.sources.length > 0 && (
            <div className="mt-2 w-full">
              <button
                type="button"
                onClick={() =>
                  setSourcesOpen((open) => !open)
                }
                className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs font-medium text-muted-light hover:bg-paper-alt dark:text-muted-dark dark:hover:bg-ink-raised transition-colors"
              >
                {sourcesOpen ? (
                  <ChevronUp size={14} />
                ) : (
                  <ChevronDown size={14} />
                )}

                Sources

                <span className="opacity-60">
                  {message.research.sources.length}
                </span>
              </button>

              {sourcesOpen && (
                <div className="mt-1 flex flex-col gap-1 rounded-xl border border-border-light p-2 dark:border-border-dark">
                  {message.research.sources.map(
                    (source, index) => (
                      <a
                        key={`${source.url}-${index}`}
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center justify-between gap-3 rounded-lg px-2.5 py-2 text-xs hover:bg-paper-alt dark:hover:bg-ink-raised transition-colors"
                      >
                        <div className="min-w-0">
                          <span className="mr-2 text-muted-light dark:text-muted-dark">
                            {index + 1}.
                          </span>

                          <span className="break-words">
                            {source.title}
                          </span>
                        </div>

                        <ExternalLink
                          size={13}
                          className="shrink-0 opacity-60"
                        />
                      </a>
                    )
                  )}
                </div>
              )}
            </div>
          )}

        <div
          className={clsx(
            'flex items-center gap-2 mt-1 px-1',
            isUser
              ? 'flex-row-reverse'
              : 'flex-row'
          )}
        >
          <span className="text-[11px] text-muted-light dark:text-muted-dark">
            {formatTime(message.createdAt)}
          </span>

          {!isEmpty &&
            !message.error &&
            !message.image && (
              <MessageActions
                content={message.content}
                showRegenerate={
                  !isUser && showRegenerate
                }
                onRegenerate={onRegenerate}
                disabled={isStreaming}
              />
            )}
        </div>
      </div>
    </div>
  );
}