import { useState } from 'react';
import clsx from 'clsx';

import {
  AlertCircle,
  ChevronDown,
  ChevronUp,
  ExternalLink,
} from 'lucide-react';

import { MarkdownRenderer } from './MarkdownRenderer';
import { TypingIndicator } from './TypingIndicator';
import { MessageActions } from './MessageActions';

import { formatTime } from '@/utils/formatDate';

import type { Message } from '@/types';

interface MessageBubbleProps {
  message: Message;
  isStreamingPlaceholder: boolean;
  showRegenerate: boolean;
  onRegenerate: () => void;
  isStreaming: boolean;
}

export function MessageBubble({
  message,
  isStreamingPlaceholder,
  showRegenerate,
  onRegenerate,
  isStreaming,
}: MessageBubbleProps) {
  const isUser =
    message.role === 'user';
    const research =
  message.research ??
  message.metadata?.research;

  const [sourcesOpen, setSourcesOpen] =
    useState(false);

  const isEmpty =
    isStreamingPlaceholder &&
    message.content.length === 0 &&
    !message.error;

  return (
    <div
      className={clsx(
        'group flex w-full px-1',
        isUser
          ? 'justify-end'
          : 'justify-start'
      )}
    >
      <div
        className={clsx(
          'flex min-w-0 flex-col',
          isUser
            ? 'max-w-[82%] items-end sm:max-w-[72%]'
            : 'w-full items-start'
        )}
      >
        {isUser ? (
          <div
            className="
              rounded-[20px]
              rounded-br-[7px]
              bg-[#1b1f27]
              px-4
              py-2.5
              text-[0.95rem]
              leading-relaxed
              text-white
              shadow-sm
              dark:bg-[#20242d]
            "
          >
            <p className="whitespace-pre-wrap break-words">
              {message.content}
            </p>

            {message.stopped && (
              <p className="mt-1.5 text-xs italic opacity-70">
                Generation stopped.
              </p>
            )}
          </div>
        ) : (
          <div className="w-full min-w-0">
            {isEmpty ? (
              <div className="py-1">
                <TypingIndicator />
              </div>
            ) : message.error ? (
              <div
                className="
                  flex items-start gap-2
                  rounded-xl
                  border border-red-500/20
                  bg-red-500/[0.06]
                  px-3.5 py-3
                  text-danger-light
                  dark:text-danger-dark
                "
              >
                <AlertCircle
                  size={16}
                  className="mt-0.5 shrink-0"
                />

                <span className="text-sm">
                  {message.error}
                </span>
              </div>
            ) : message.image ? (
              <div className="overflow-hidden rounded-2xl">
                <img
                  src={`data:${message.image.mimeType};base64,${message.image.data}`}
                  alt={
                    message.image.alt ??
                    'Generated by Atlas AI'
                  }
                  className="
                    max-h-[650px]
                    max-w-full
                    rounded-2xl
                    object-contain
                  "
                />
              </div>
            ) : (
              <div
                className="
                  w-full
                  text-[0.97rem]
                  leading-7
                  text-ink
                  dark:text-paper
                "
              >
                <MarkdownRenderer
                  content={
                    message.content
                  }
                />
              </div>
            )}

            {message.stopped &&
              !message.image && (
                <p className="mt-2 text-xs italic text-muted-light dark:text-muted-dark">
                  Generation stopped.
                </p>
              )}
          </div>
        )}

        {message.research &&
          message.research.sources.length >
            0 && (
            <div
              className={clsx(
                'mt-3',
                isUser
                  ? 'w-full'
                  : 'w-full max-w-2xl'
              )}
            >
              <button
                type="button"
                onClick={() =>
                  setSourcesOpen(
                    (open) => !open
                  )
                }
                className="
                  flex items-center
                  gap-1.5
                  rounded-lg
                  px-2 py-1.5
                  text-xs
                  font-medium
                  text-muted-light
                  transition
                  hover:bg-black/[0.04]
                  dark:text-muted-dark
                  dark:hover:bg-white/[0.06]
                "
              >
                {sourcesOpen ? (
                  <ChevronUp
                    size={14}
                  />
                ) : (
                  <ChevronDown
                    size={14}
                  />
                )}

                Sources

                <span className="opacity-60">
                  {
                    message.research
                      .sources.length
                  }
                </span>
              </button>

              {sourcesOpen && (
                <div
                  className="
                    mt-1
                    flex flex-col
                    gap-1
                    rounded-xl
                    border border-black/[0.07]
                    bg-black/[0.02]
                    p-2
                    dark:border-white/[0.08]
                    dark:bg-white/[0.03]
                  "
                >
                  {message.research.sources.map(
                    (
                      source,
                      index
                    ) => (
                      <a
                        key={`${source.url}-${index}`}
                        href={
                          source.url
                        }
                        target="_blank"
                        rel="noopener noreferrer"
                        className="
                          flex
                          items-center
                          justify-between
                          gap-3
                          rounded-lg
                          px-2.5
                          py-2
                          text-xs
                          transition
                          hover:bg-black/[0.04]
                          dark:hover:bg-white/[0.06]
                        "
                      >
                        <div className="min-w-0">
                          <span className="mr-2 text-muted-light dark:text-muted-dark">
                            {index +
                              1}
                            .
                          </span>

                          <span className="break-words">
                            {
                              source.title
                            }
                          </span>
                        </div>

                        <ExternalLink
                          size={13}
                          className="shrink-0 opacity-60"
                        />
                      </a>
                    )
                  )}
                </div>
              )}
            </div>
          )}

        <div
          className={clsx(
            'mt-1.5 flex items-center gap-2 px-1',
            isUser
              ? 'flex-row-reverse'
              : 'flex-row'
          )}
        >
          <span className="text-[10px] text-muted-light/80 dark:text-muted-dark/80">
            {formatTime(
              message.createdAt
            )}
          </span>

          {!isEmpty &&
            !message.error &&
            !message.image && (
              <MessageActions
                content={
                  message.content
                }
                showRegenerate={
                  !isUser &&
                  showRegenerate
                }
                onRegenerate={
                  onRegenerate
                }
                disabled={
                  isStreaming
                }
              />
            )}
        </div>
      </div>
    </div>
  );
}